# fly.toml app configuration file generated for uoacs-website on 2026-01-13T21:00:50+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uoacs-website-staging'
primary_region = 'syd'
swap_size_mb = 256

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  cpu_kind = 'shared'
