import type { Member } from "@/payload/payload-types"

type SkillValue = NonNullable<Member["skills"]>[number]

export const skills = [
  // Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Dart",
  "Ruby",
  "PHP",
  "Scala",
  "R",
  "MATLAB",
  "Haskell",
  "Lua",
  "Bash",
  "SQL",
  "HTML/CSS",
  // Web
  "React",
  "Next.js",
  "Vue",
  "Svelte",
  "Angular",
  "Tailwind CSS",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Ruby on Rails",
  "Laravel",
  "GraphQL",
  "REST APIs",
  // Mobile
  "Mobile Development",
  "iOS Development",
  "Android Development",
  "React Native",
  "Flutter",
  // Data and AI
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Data Science",
  "Data Analysis",
  "Data Engineering",
  "Data Visualisation",
  "Statistics",
  "PyTorch",
  "TensorFlow",
  "Pandas",
  // Infrastructure
  "DevOps",
  "Cloud Computing",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Linux",
  "Networking",
  "Databases",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  // Other technical
  "Cybersecurity",
  "Algorithms",
  "Operating Systems",
  "Embedded Systems",
  "Robotics",
  "Blockchain",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "AR/VR",
  "Testing",
  "Git",
  "Open Source",
  // Design
  "UI/UX Design",
  "Graphic Design",
  "Figma",
  "Motion Design",
  "3D Modelling",
  "Video Editing",
  "Photography",
  // Professional
  "Product Management",
  "Project Management",
  "Agile",
  "Leadership",
  "Teamwork",
  "Public Speaking",
  "Technical Writing",
  "Entrepreneurship",
  "Marketing",
] as const satisfies readonly SkillValue[]
