# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy Staging
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app to staging
    runs-on: ubuntu-latest
    concurrency: staging-deploy-group
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Deploy to Fly.io
        uses: ./.github/actions/fly-deploy
        with:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          APP_NAME: uoacs-website-staging
          CONFIG_FILE: apps/website/fly.staging.toml
          DOCKERFILE: apps/website/Dockerfile
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          NEXT_PUBLIC_WEBSITE_URL: ${{ vars.NEXT_PUBLIC_WEBSITE_URL }}
          NEXT_PUBLIC_PROJECTS_URL: ${{ vars.NEXT_PUBLIC_PROJECTS_URL }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          GOOGLE_WALLET_ISSUER_ID: ${{ secrets.GOOGLE_WALLET_ISSUER_ID }}
          GOOGLE_WALLET_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_WALLET_SERVICE_ACCOUNT_KEY }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
