name: PR Notification

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
  release:
    types: [published]

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Send notification for PR Ready for Review
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == false && (github.event.action == 'ready_for_review' || github.event.action == 'opened' || github.event.action == 'reopened')
        uses: taroj1205/discord-notification@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: 6385919
          title: 'PR Ready for Review: ${{ github.event.pull_request.title }}'
          description: ${{ github.event.pull_request.body }}
          description_max_length: 175
          url: ${{ github.event.pull_request.html_url }}
          author_name: ${{ github.event.pull_request.user.login }}
          author_url: ${{ github.event.pull_request.user.html_url }}
          author_icon_url: ${{ github.event.pull_request.user.avatar_url }}
          image_url: 'https://opengraph.githubassets.com/${{ github.sha }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}'
          button_label: 'View Pull Request'
          branch_info: '`${{ github.event.pull_request.head.ref }}` -> `${{ github.event.pull_request.base.ref }}`'

      - name: Send notification on PR Merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: taroj1205/discord-notification@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: 3901276
          title: 'PR Merged: ${{ github.event.pull_request.title }}'
          description: 'The pull request was merged by **${{ github.event.pull_request.merged_by.login }}**.'
          url: ${{ github.event.pull_request.html_url }}
          author_name: ${{ github.event.pull_request.user.login }}
          author_url: ${{ github.event.pull_request.user.html_url }}
          author_icon_url: ${{ github.event.pull_request.user.avatar_url }}
          image_url: 'https://opengraph.githubassets.com/${{ github.sha }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}'
          button_label: 'View Merged PR'
          branch_info: '`${{ github.event.pull_request.head.ref }}` -> `${{ github.event.pull_request.base.ref }}`'

      - name: Send notification on PR Closed
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
        uses: taroj1205/discord-notification@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: 16076400
          title: 'PR Closed: ${{ github.event.pull_request.title }}'
          description: 'The pull request was closed without merging.'
          url: ${{ github.event.pull_request.html_url }}
          author_name: ${{ github.event.pull_request.user.login }}
          author_url: ${{ github.event.pull_request.user.html_url }}
          author_icon_url: ${{ github.event.pull_request.user.avatar_url }}
          image_url: 'https://opengraph.githubassets.com/${{ github.sha }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}'
          button_label: 'View Closed PR'

      - name: Send notification on New Release
        if: github.event_name == 'release'
        uses: taroj1205/discord-notification@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: 3447003
          title: 'New Release: ${{ github.event.release.tag_name }}'
          description: ${{ github.event.release.body }}
          description_max_length: 175
          url: ${{ github.event.release.html_url }}
          author_name: ${{ github.event.release.author.login }}
          author_url: ${{ github.event.release.author.html_url }}
          author_icon_url: ${{ github.event.release.author.avatar_url }}
          image_url: 'https://opengraph.githubassets.com/${{ github.sha }}/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}'
          button_label: 'View Release'
